server {
    listen 8080;

    # Root location for all requests
    location / {
        root /usr/share/nginx/html/public;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Serve static files correctly
    location /static/ {
        root /usr/share/nginx/html/public;
        try_files $uri $uri/ =404;
    }
}
